language: node_js
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
install:
  - npm install nodeunit -g
  - npm install istanbul -g
  - npm install codecov -g
  - npm install happiness -g
  - npm install eclint@2.2.0 -g
script:
  - istanbul cover nodeunit tests/testmain.js
  - eclint check "{tests,extensions}/*.js"
  - eclint check "*.{js,html,json}"
branches:
  only:
    - gh-pages
    - master
after_success:
  codecov -t $CODECOV_TOKEN
