language: node_js
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
install:
  - npm install nodeunit -g
  # below modules required for testing decimal.js
  - npm install decimal.js
script:
  - npm test
  - nodeunit tests/testdecimal.js
branches:
  only:
    - gh-pages
    - master